name: Setup
description: Setup pnpm and Node.js, then install dependencies
runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
